package net.everla.everlaartifacts.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.everla.everlaartifacts.common.item.weird_thing.ZakoUncleItem;
import net.everla.everlaartifacts.common.item.weird_thing.WeirdCocktailItem;
import net.everla.everlaartifacts.common.item.VenusShellItem;
import net.everla.everlaartifacts.common.item.WitherEssenceItem;
import net.everla.everlaartifacts.common.item.TwoBreadSandwichedWithCheeseItem;
import net.everla.everlaartifacts.common.item.weird_thing.TokyoTicketItem;
import net.everla.everlaartifacts.common.item.ThreeInterwinedFateItem;
import net.everla.everlaartifacts.common.item.RedPacketItem;
import net.everla.everlaartifacts.common.item.RawAuricItem;
import net.everla.everlaartifacts.common.item.ProcedureSwordItem;
import net.everla.everlaartifacts.common.item.weird_thing.PotOfPainItem;
import net.everla.everlaartifacts.common.item.weird_thing.p2wshard.PayToWinShard5Item;
import net.everla.everlaartifacts.common.item.weird_thing.p2wshard.PayToWinShard4Item;
import net.everla.everlaartifacts.common.item.weird_thing.p2wshard.PayToWinShard3Item;
import net.everla.everlaartifacts.common.item.weird_thing.p2wshard.PayToWinShard2Item;
import net.everla.everlaartifacts.common.item.weird_thing.p2wshard.PayToWinShard1Item;
import net.everla.everlaartifacts.common.item.weird_thing.PayToWinCrystalItem;
import net.everla.everlaartifacts.common.item.NuclearWasteWaterItem;
import net.everla.everlaartifacts.common.item.weird_thing.NilkItem;
import net.everla.everlaartifacts.common.item.weird_thing.NanjingTicketItem;
import net.everla.everlaartifacts.common.item.InnerQuartzOuterNuclearItem;
import net.everla.everlaartifacts.common.item.HomaStaffItem;
import net.everla.everlaartifacts.common.item.FirecrackerItem;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato9Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato8Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato7Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato6Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato5Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato4Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato3Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato2Item;
import net.everla.everlaartifacts.common.item.weird_thing.potatos.CondencedPotato1Item;
import net.everla.everlaartifacts.common.item.weird_thing.ChineseDumplingItem;
import net.everla.everlaartifacts.common.item.weird_thing.ChaliceOfBloodGodItem;
import net.everla.everlaartifacts.common.item.BraisedPorkWithPlumCabbageItem;
import net.everla.everlaartifacts.common.item.BracketsBladeItem;
import net.everla.everlaartifacts.common.item.weird_thing.BeijingTicketItem;
import net.everla.everlaartifacts.common.item.AuricScrapItem;
import net.everla.everlaartifacts.common.item.AuricScrapBlockItem;
import net.everla.everlaartifacts.common.item.AuricIngotItem;
import net.everla.everlaartifacts.common.item.weird_thing.WeirdFishStewItem;
import net.everla.everlaartifacts.common.item.DragonSoulFragmentItem;
import net.everla.everlaartifacts.common.item.GigabyteMemoryRingItem;
import net.everla.everlaartifacts.EverlaartifactsMod;

public class EverlaartifactsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, EverlaartifactsMod.MODID);
	public static final RegistryObject<Item> DEEPSLATE_AURIC_ORE = block(EverlaartifactsModBlocks.DEEPSLATE_AURIC_ORE);
	public static final RegistryObject<Item> RAW_AURIC = REGISTRY.register("raw_auric", () -> new RawAuricItem());
	public static final RegistryObject<Item> AURIC_SCRAP = REGISTRY.register("auric_scrap", () -> new AuricScrapItem());
	public static final RegistryObject<Item> AURIC_INGOT = REGISTRY.register("auric_ingot", () -> new AuricIngotItem());
	public static final RegistryObject<Item> ZAKO_UNCLE = REGISTRY.register("zako_uncle", () -> new ZakoUncleItem());
	public static final RegistryObject<Item> POT_OF_PAIN = REGISTRY.register("pot_of_pain", () -> new PotOfPainItem());
	public static final RegistryObject<Item> CHINESE_DUMPLING = REGISTRY.register("chinese_dumpling", () -> new ChineseDumplingItem());
	public static final RegistryObject<Item> RED_PACKET = REGISTRY.register("red_packet", () -> new RedPacketItem());
	public static final RegistryObject<Item> NUCLEAR_WASTE_WATER_BUCKET = REGISTRY.register("nuclear_waste_water_bucket", () -> new NuclearWasteWaterItem());
	public static final RegistryObject<Item> INNER_QUARTZ_OUTER_NUCLEAR = REGISTRY.register("inner_quartz_outer_nuclear", () -> new InnerQuartzOuterNuclearItem());
	public static final RegistryObject<Item> TWO_BREAD_SANDWICHED_WITH_CHEESE = REGISTRY.register("two_bread_sandwiched_with_cheese", () -> new TwoBreadSandwichedWithCheeseItem());
	public static final RegistryObject<Item> THREE_INTERWINED_FATE = REGISTRY.register("three_interwined_fate", () -> new ThreeInterwinedFateItem());
	public static final RegistryObject<Item> WEIRD_COCKTAIL = REGISTRY.register("weird_cocktail", () -> new WeirdCocktailItem());
	public static final RegistryObject<Item> BRAISED_PORK_WITH_PLUM_CABBAGE = REGISTRY.register("braised_pork_with_plum_cabbage", () -> new BraisedPorkWithPlumCabbageItem());
	public static final RegistryObject<Item> PAY_TO_WIN_SHARD_1 = REGISTRY.register("pay_to_win_shard_1", () -> new PayToWinShard1Item());
	public static final RegistryObject<Item> PAY_TO_WIN_SHARD_2 = REGISTRY.register("pay_to_win_shard_2", () -> new PayToWinShard2Item());
	public static final RegistryObject<Item> PAY_TO_WIN_SHARD_3 = REGISTRY.register("pay_to_win_shard_3", () -> new PayToWinShard3Item());
	public static final RegistryObject<Item> PAY_TO_WIN_SHARD_4 = REGISTRY.register("pay_to_win_shard_4", () -> new PayToWinShard4Item());
	public static final RegistryObject<Item> PAY_TO_WIN_SHARD_5 = REGISTRY.register("pay_to_win_shard_5", () -> new PayToWinShard5Item());
	public static final RegistryObject<Item> PAY_TO_WIN_CRYSTAL = REGISTRY.register("pay_to_win_crystal", () -> new PayToWinCrystalItem());
	public static final RegistryObject<Item> FIRECRACKER = REGISTRY.register("firecracker", () -> new FirecrackerItem());
	public static final RegistryObject<Item> BEIJING_TICKET = REGISTRY.register("beijing_ticket", () -> new BeijingTicketItem());
	public static final RegistryObject<Item> NANJING_TICKET = REGISTRY.register("nanjing_ticket", () -> new NanjingTicketItem());
	public static final RegistryObject<Item> TOKYO_TICKET = REGISTRY.register("tokyo_ticket", () -> new TokyoTicketItem());
	public static final RegistryObject<Item> CONDENCED_POTATO_1 = REGISTRY.register("condenced_potato_1", () -> new CondencedPotato1Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_2 = REGISTRY.register("condenced_potato_2", () -> new CondencedPotato2Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_3 = REGISTRY.register("condenced_potato_3", () -> new CondencedPotato3Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_4 = REGISTRY.register("condenced_potato_4", () -> new CondencedPotato4Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_5 = REGISTRY.register("condenced_potato_5", () -> new CondencedPotato5Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_6 = REGISTRY.register("condenced_potato_6", () -> new CondencedPotato6Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_7 = REGISTRY.register("condenced_potato_7", () -> new CondencedPotato7Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_8 = REGISTRY.register("condenced_potato_8", () -> new CondencedPotato8Item());
	public static final RegistryObject<Item> CONDENCED_POTATO_9 = REGISTRY.register("condenced_potato_9", () -> new CondencedPotato9Item());
	public static final RegistryObject<Item> CHALICE_OF_BLOOD_GOD = REGISTRY.register("chalice_of_blood_god", () -> new ChaliceOfBloodGodItem());
	public static final RegistryObject<Item> HOMA_STAFF = REGISTRY.register("homa_staff", () -> new HomaStaffItem());
	public static final RegistryObject<Item> NILK = REGISTRY.register("nilk", () -> new NilkItem());
	public static final RegistryObject<Item> VENUS_SHELL = REGISTRY.register("venus_shell", () -> new VenusShellItem());
	public static final RegistryObject<Item> BRACKETS_BLADE = REGISTRY.register("brackets_blade", () -> new BracketsBladeItem());
	public static final RegistryObject<Item> PROCEDURE_SWORD = REGISTRY.register("procedure_sword", () -> new ProcedureSwordItem());
	public static final RegistryObject<Item> WEIRD_FISH_STEW = REGISTRY.register("weird_fish_stew", () -> new WeirdFishStewItem());
	public static final RegistryObject<Item> DRAGON_SOUL_FRAGMENT = REGISTRY.register("dragon_soul_fragment", () -> new DragonSoulFragmentItem());
	public static final RegistryObject<Item> AURIC_SCRAP_BLOCK = REGISTRY.register("auric_scrap_block", () -> new AuricScrapBlockItem(EverlaartifactsModBlocks.AURIC_SCRAP_BLOCK.get()));
	public static final RegistryObject<Item> WITHER_ESSENCE = REGISTRY.register("wither_essence", () -> new WitherEssenceItem());
	public static final RegistryObject<Item> GIGABYTE_MEMORY_RING = REGISTRY.register("gigabyte_memory_ring", () -> new GigabyteMemoryRingItem());
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
